/** Hierarchical TanStack Query keys: everything of a career lives under ['career', id, …]. */
export const qk = {
  me: ['me'] as const,
  sessions: ['me', 'sessions'] as const,
  careers: ['careers'] as const,
  locationSearch: (q: string) => ['locations', 'search', q] as const,
  starterSites: (locationId: string) => ['locations', locationId, 'starter-sites'] as const,
  career: (id: string) => ['career', id] as const,
  sync: (id: string) => ['career', id, 'sync'] as const,
  catalog: (id: string) => ['career', id, 'catalog'] as const,
  awayReport: (id: string) => ['career', id, 'away-report'] as const,
  facility: (id: string, facilityId: string) => ['career', id, 'facility', facilityId] as const,
  dispatchOptions: (id: string, incidentId: string) =>
    ['career', id, 'incident', incidentId, 'dispatch-options'] as const,
  timeline: (id: string, incidentId: string) => ['career', id, 'incident', incidentId, 'timeline'] as const,
  balance: (id: string) => ['career', id, 'economy', 'balance'] as const,
  ledger: (id: string) => ['career', id, 'economy', 'ledger'] as const,
  stipend: (id: string) => ['career', id, 'economy', 'stipend'] as const,
  progression: (id: string) => ['career', id, 'progression'] as const,
  unlocks: (id: string) => ['career', id, 'progression', 'unlocks'] as const,
  notifications: (id: string) => ['career', id, 'notifications'] as const,
  /* web push (D-97…D-99): the server's switch + categories, and the career's categories / quiet hours */
  pushConfig: ['push', 'config'] as const,
  pushPreferences: (id: string) => ['career', id, 'push', 'preferences'] as const,
  milestones: (id: string) => ['career', id, 'progression', 'milestones'] as const,
  /* depth domains — everything of a domain lives under its root key so one realtime event invalidates it all */
  personnelRoot: (id: string) => ['career', id, 'personnel'] as const,
  personnel: (id: string) => ['career', id, 'personnel', 'list'] as const,
  personnelDetail: (id: string, personnelId: string) =>
    ['career', id, 'personnel', 'detail', personnelId] as const,
  candidates: (id: string) => ['career', id, 'personnel', 'candidates'] as const,
  teams: (id: string) => ['career', id, 'personnel', 'teams'] as const,
  departments: (id: string) => ['career', id, 'personnel', 'departments'] as const,
  training: (id: string) => ['career', id, 'personnel', 'training'] as const,
  medicalRoot: (id: string) => ['career', id, 'medical'] as const,
  patients: (id: string, incidentId: string) => ['career', id, 'medical', 'patients', incidentId] as const,
  hospitalOptions: (id: string, patientId: string) =>
    ['career', id, 'medical', 'options', patientId] as const,
  hospitals: (id: string) => ['career', id, 'medical', 'hospitals'] as const,
  waterSources: (id: string, incidentId: string) => ['career', id, 'water-sources', incidentId] as const,
  /* major incidents (D-24 / D-69): the coordination view, its reinforcement quote, the history and the trophies */
  majorRoot: (id: string) => ['career', id, 'major'] as const,
  majorCurrent: (id: string) => ['career', id, 'major', 'current'] as const,
  major: (id: string, majorId: string) => ['career', id, 'major', 'detail', majorId] as const,
  majorList: (id: string) => ['career', id, 'major', 'list'] as const,
  majorTrophies: (id: string) => ['career', id, 'major', 'trophies'] as const,
  inventory: (id: string) => ['career', id, 'inventory'] as const,
  inventoryItems: (id: string) => ['career', id, 'inventory', 'items'] as const,
  maintenance: (id: string) => ['career', id, 'maintenance'] as const,
  vehicleHistory: (id: string, vehicleId: string) =>
    ['career', id, 'maintenance', 'history', vehicleId] as const,
  worldRoot: (id: string) => ['career', id, 'world'] as const,
  coverage: (id: string) => ['career', id, 'world', 'coverage'] as const,
  sites: (id: string, bbox: string) => ['career', id, 'world', 'sites', bbox] as const,
  runways: (id: string, bbox: string) => ['career', id, 'world', 'runways', bbox] as const,
  monetizationRoot: (id: string) => ['career', id, 'monetization'] as const,
  packages: (id: string) => ['career', id, 'monetization', 'packages'] as const,
  purchases: (id: string) => ['career', id, 'monetization', 'purchases'] as const,
  savedPaymentMethod: (id: string) => ['career', id, 'monetization', 'payment-method'] as const,
  adsStatus: (id: string) => ['career', id, 'monetization', 'ads'] as const,
  referrals: (id: string) => ['career', id, 'monetization', 'referrals'] as const,
  speedupQuote: (id: string, target: string, targetId: string) =>
    ['career', id, 'monetization', 'speedup', target, targetId] as const,
  admin: (resource: string, ...rest: unknown[]) => ['admin', resource, ...rest] as const,
  /* alliances (D-102…D-123): everything of the career's alliance under one root — the alliance stream invalidates it */
  allianceRoot: (id: string) => ['career', id, 'alliance'] as const,
  allianceHome: (id: string) => ['career', id, 'alliance', 'home'] as const,
  allianceMembers: (id: string) => ['career', id, 'alliance', 'members'] as const,
  allianceJoinRequests: (id: string) => ['career', id, 'alliance', 'join-requests'] as const,
  allianceInvites: (id: string) => ['career', id, 'alliance', 'invites'] as const,
  allianceLog: (id: string) => ['career', id, 'alliance', 'log'] as const,
  allianceBoard: (id: string) => ['career', id, 'alliance', 'board'] as const,
  allianceBoardReplies: (id: string, postId: string) =>
    ['career', id, 'alliance', 'board', 'replies', postId] as const,
  allianceChat: (id: string) => ['career', id, 'alliance', 'chat'] as const,
  allianceChannels: (id: string) => ['career', id, 'alliance', 'chat', 'channels'] as const,
  allianceMessages: (id: string, channelId: string) =>
    ['career', id, 'alliance', 'chat', 'messages', channelId] as const,
  alliancePresence: (id: string) => ['career', id, 'alliance', 'chat', 'presence'] as const,
  allianceAid: (id: string) => ['career', id, 'alliance', 'aid'] as const,
  allianceAidRequests: (id: string, status: 'OPEN' | 'ALL') =>
    ['career', id, 'alliance', 'aid', 'requests', status] as const,
  allianceAidRequest: (id: string, requestId: string) =>
    ['career', id, 'alliance', 'aid', 'request', requestId] as const,
  allianceAidColumns: (id: string, role: string, active: boolean) =>
    ['career', id, 'alliance', 'aid', 'columns', role, active] as const,
  allianceColumnOptions: (id: string, requestId: string) =>
    ['career', id, 'alliance', 'aid', 'options', requestId] as const,
  allianceProgress: (id: string) => ['career', id, 'alliance', 'progress'] as const,
  allianceOperation: (id: string) => ['career', id, 'alliance', 'operation'] as const,
  allianceObjectives: (id: string) => ['career', id, 'alliance', 'progress', 'objectives'] as const,
  allianceXp: (id: string) => ['career', id, 'alliance', 'progress', 'xp'] as const,
  allianceOperations: (id: string) => ['career', id, 'alliance', 'operation', 'history'] as const,
  allianceSearch: (query: string) => ['alliances', 'search', query] as const,
  allianceCard: (allianceId: string) => ['alliances', 'card', allianceId] as const,
  allianceRanking: ['alliances', 'ranking'] as const,
  publicAllianceInvite: (code: string) => ['public', 'alliance-invite', code] as const,
  directorCard: (careerId: string) => ['directors', careerId] as const,
  directorSearch: (q: string) => ['directors', 'search', q] as const,
  profile: ['me', 'profile'] as const,
  communityRules: ['me', 'community-rules'] as const,
  blocks: (id: string) => ['career', id, 'blocks'] as const,
};
