'use client';
import * as React from 'react';
import Link from 'next/link';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useLocale, useTranslations } from 'next-intl';
import { BadgeCheck, CheckCircle2, Hammer, Lock, MapPin, Sparkles } from 'lucide-react';
import type { SiteDto, SyncSnapshot } from '@/contracts';
import { facilitiesApi } from '@/lib/api/depth';
import { qk } from '@/lib/api/query-keys';
import { isApiError } from '@/lib/api/errors';
import { track } from '@/lib/analytics';
import { compareAmount, formatClock, formatDistance } from '@/lib/format';
import { haversineMeters } from '@/lib/geo';
import { toast } from '@/stores/toast';
import { useCatalogName } from '@/i18n/use-i18n-text';
import { FamilyBadge, type AnyFamily } from '@/design/icons';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { CreditAmount } from '@/components/ui/credit-amount';
import { SectionTitle, Stat } from '@/components/ui/misc';
import { requestCredits } from '@/features/monetization/insufficient-credits';
import { useFamilies } from '@/features/families/use-families';
import { useCareerId, useCatalog, useSnapshot } from '@/features/game/hooks';
import { NauticalConditions } from '@/features/water/nautical';
import { useFixItToast } from './error-fix';

type SiteOption = SiteDto['options'][number];

/** Family shown for a site: a site that only offers SHARED facility types is a shared (coordination) site. */
export const siteFamily = (site: SiteDto): AnyFamily =>
  site.options.length > 0 && site.options.every((o) => o.family === 'SHARED') ? 'SHARED' : site.family;

/** Family label including the SHARED pseudo-family (not a service family, so not in the catalog bundle). */
export function useFamilyLabel(): (family: AnyFamily) => string {
  const t = useTranslations('facilities.site');
  const name = useCatalogName();
  return React.useCallback(
    (family) => (family === 'SHARED' ? t('sharedFamily') : name('family', family)),
    [t, name],
  );
}

/** "Real place" vs "generated by the game" — always icon + label. */
export function SiteOriginBadge({ site }: { site: Pick<SiteDto, 'real'> }) {
  const t = useTranslations('facilities.site');
  return site.real ? (
    <Badge tone="info" title={t('realHint')} data-testid="site-origin" data-real="true">
      <BadgeCheck className="size-3" aria-hidden />
      {t('real')}
    </Badge>
  ) : (
    <Badge title={t('generatedHint')} data-testid="site-origin" data-real="false">
      <Sparkles className="size-3" aria-hidden />
      {t('generated')}
    </Badge>
  );
}

function OptionRow({
  site,
  option,
  onAcquired,
}: {
  site: SiteDto;
  option: SiteOption;
  onAcquired?: (facilityId: string) => void;
}) {
  const careerId = useCareerId();
  const t = useTranslations('facilities.site');
  const td = useTranslations('game.facility');
  const tc = useTranslations('common');
  const name = useCatalogName();
  const qc = useQueryClient();
  const fixItToast = useFixItToast();
  const catalog = useCatalog();
  const families = useFamilies();
  const { career } = useSnapshot();
  const type = catalog?.facilityTypes.find((f) => f.code === option.facilityTypeCode);
  const affordable = compareAmount(career.credits, option.price) >= 0;
  const acquire = useMutation({
    mutationFn: () =>
      facilitiesApi.acquire(careerId, { siteId: site.id, facilityTypeCode: option.facilityTypeCode }),
    onSuccess: (facility) => {
      track('facility_acquired', { type: option.facilityTypeCode, family: option.family, real: site.real });
      // The realtime event patches the snapshot too; doing it here makes the new facility selectable at once.
      qc.setQueryData<SyncSnapshot>(qk.sync(careerId), (s) =>
        s && !s.facilities.some((f) => f.id === facility.id)
          ? { ...s, facilities: [...s.facilities, facility] }
          : s,
      );
      void qc.invalidateQueries({ queryKey: qk.worldRoot(careerId) });
      toast({
        tone: 'success',
        title: t('acquired', { name: facility.name }),
        description: t('acquiredHint'),
      });
      onAcquired?.(facility.id);
    },
    // NAUTICAL_SITE_REQUIRED and the other refusals come with where to go to fix them.
    onError: (e) => {
      if (isApiError(e, 'INSUFFICIENT_CREDITS')) requestCredits(option.price);
      else fixItToast(e, { family: option.family });
    },
  });
  // The site's garage size applies to the types that have a garage (a Base nautica keeps boats only, D-23).
  const hasGarage = type?.domains.includes('GROUND') ?? true;
  const capacity = (['GROUND', 'AIR', 'WATER', 'PERSONNEL'] as const)
    .map((d) => ({
      d,
      n:
        d === 'GROUND' && hasGarage
          ? Math.max(site.capacityPoints, type?.baseCapacity[d] ?? 0)
          : (type?.baseCapacity[d] ?? 0),
    }))
    .filter((x) => x.n > 0);
  const familyLevel = families.find((f) => f.code === option.family)?.requiredLevel ?? option.requiredLevel;
  return (
    <li
      className="border-border bg-surface-2 flex flex-col gap-2 rounded-md border p-3"
      data-testid="site-option"
      data-type={option.facilityTypeCode}
      data-available={option.available}
    >
      <div className="flex items-start gap-2.5">
        <FamilyBadge family={option.family} size={32} title={name('family', option.family)} />
        <div className="min-w-0 flex-1">
          <p className="text-sm font-semibold">{name('facility', option.facilityTypeCode)}</p>
          <p
            className="text-muted line-clamp-2 text-xs"
            title={name('facility', option.facilityTypeCode, 'description')}
          >
            {name('facility', option.facilityTypeCode, 'description')}
          </p>
        </div>
        <Badge>{t('tier', { tier: option.tier })}</Badge>
      </div>
      <ul className="text-muted flex flex-wrap gap-x-3 gap-y-0.5 text-xs">
        {capacity.map(({ d, n }) => (
          <li key={d}>
            {td(`domain.${d}`)} <span className="tabular text-fg">{n}</span>
          </li>
        ))}
        <li className="flex items-center gap-1">
          <Hammer className="size-3" aria-hidden />
          {t('setup')} <span className="tabular text-fg">{formatClock(option.setupSeconds)}</span>
        </li>
      </ul>
      {option.available ? (
        <Button
          variant={affordable ? 'primary' : 'outline'}
          className="justify-between"
          loading={acquire.isPending}
          onClick={() => (affordable ? acquire.mutate() : requestCredits(option.price))}
          data-testid="acquire-facility"
        >
          <span>{t('acquire')}</span>
          <CreditAmount value={option.price} label={tc('credits')} tone={affordable ? 'plain' : 'credits'} />
        </Button>
      ) : (
        <p
          className="border-border-strong text-muted flex min-h-10 items-center justify-between gap-2 rounded-md border border-dashed px-3 py-1.5 text-xs"
          data-testid="site-option-locked"
          data-reason={option.lockedReason ?? undefined}
        >
          <span className="flex items-center gap-1.5">
            {option.lockedReason === 'SITE_NOT_AVAILABLE' ? (
              <CheckCircle2 className="size-3.5 shrink-0" aria-hidden />
            ) : (
              <Lock className="size-3.5 shrink-0" aria-hidden />
            )}
            {option.lockedReason === 'NOT_UNLOCKED'
              ? t('lockedFamily', { level: familyLevel })
              : option.lockedReason === 'SITE_NOT_AVAILABLE'
                ? t('alreadyOwned')
                : tc('requiresLevel', { level: option.requiredLevel })}
          </span>
          <CreditAmount value={option.price} label={tc('credits')} size="sm" tone="plain" />
        </p>
      )}
    </li>
  );
}

/** Body shared by the map inspector (desktop side panel / mobile sheet) and the dialog of the facilities page. */
export function SiteDetails({
  site,
  onAcquired,
}: {
  site: SiteDto;
  onAcquired?: (facilityId: string) => void;
}) {
  const t = useTranslations('facilities.site');
  const locale = useLocale();
  const { facilities } = useSnapshot();
  const nearest = facilities.length
    ? Math.min(...facilities.map((f) => haversineMeters(f.position, site.position)))
    : null;
  const ownedFacility = site.owned
    ? [...facilities].sort(
        (a, b) => haversineMeters(a.position, site.position) - haversineMeters(b.position, site.position),
      )[0]
    : undefined;
  return (
    <div className="flex flex-col gap-4" data-testid="site-details" data-owned={site.owned}>
      {site.address ? (
        <p className="text-muted flex items-center gap-1.5 text-xs">
          <MapPin className="size-3.5 shrink-0" aria-hidden />
          {site.address}
        </p>
      ) : null}
      {site.nautical ? (
        // A nautical site (D-23): the conditions of the Base nautica instead of garage size and growth.
        <>
          <NauticalConditions site={site} />
          <Stat
            label={t('nearest')}
            value={
              <span className="text-sm">{nearest === null ? '—' : formatDistance(nearest, locale)}</span>
            }
          />
        </>
      ) : (
        <>
          <div className="grid grid-cols-3 gap-3">
            <Stat label={t('capacity')} value={site.capacityPoints} />
            <Stat
              label={t('expansion')}
              value={
                <span className="font-sans text-sm">{t(`expansionLevel.${site.expansionPotential}`)}</span>
              }
            />
            <Stat
              label={t('nearest')}
              value={
                <span className="text-sm">{nearest === null ? '—' : formatDistance(nearest, locale)}</span>
              }
            />
          </div>
          <p className="text-subtle text-xs">{t(`profile.${site.profile}`)}</p>
        </>
      )}
      {site.owned ? (
        <div className="border-success/40 bg-success/10 flex flex-col gap-2 rounded-md border p-3 text-sm">
          <span className="text-success flex items-center gap-2 font-semibold">
            <CheckCircle2 className="size-4" aria-hidden />
            {t('owned')}
          </span>
          {ownedFacility ? (
            <Button asChild variant="secondary" size="sm">
              <Link href={`/game/facilities?id=${ownedFacility.id}`}>{t('openFacility')}</Link>
            </Button>
          ) : null}
        </div>
      ) : (
        <div>
          <SectionTitle>{t('options')}</SectionTitle>
          <ul className="flex flex-col gap-2">
            {site.options.map((o) => (
              <OptionRow key={o.facilityTypeCode} site={site} option={o} onAcquired={onAcquired} />
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
